services:
  api-gateway:
    build: "./api-gateway"
    ports:
      - "5000:5001"
    env_file:
      - "./api-gateway/.env"
    depends_on:
      - media-service
    networks:
      - codeyaan-network

  auth-service:
    build: "./auth-service"
    ports:
      - "5001:5002"
    env_file:
      - "./auth-service/.env"
    networks:
      - codeyaan-network

  user-service:
    build: "./user-service"
    ports:
      - "5002:5003"
    env_file:
      - "./user-service/.env"
    networks:
      - codeyaan-network

  media-service:
    build: ./media-service
    ports:
     - "7000:7001"  
    env_file:
      - ./media-service/.env
    networks:
      - codeyaan-network
 

# 👇 existing external network use kar rahe ho
networks:
  codeyaan-network:
    external: true